services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: landing_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    image: php:8.2-apache
    container_name: php
    restart: always
    volumes:
      - ./public_html:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

volumes:
  db_data:
